# Generated by Django 4.1.2 on 2022-10-29 20:09

from django.db import migrations, models

import apps.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Token",
            ),
        ),
    ]
