# Generated by Django 4.1.2 on 2022-10-30 08:17

from django.db import migrations, models

import apps.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_user_token"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Token",
            ),
        ),
    ]
