# Generated by Django 4.1.2 on 2022-11-01 15:51

from django.db import migrations


def role_forwards_func(apps, schema_editor):
    """
    Create developer & project-manager role group
    """
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).bulk_create(
        [
            Group(name="Developer"),
            Group(name="Project Manager"),
        ]
    )


def role_reverse_func(apps, schema_editor):
    """
    delete developer & project-manager role group
    """
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).filter(name="Developer").delete()
    Group.objects.using(db_alias).filter(name="Project Manager").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers_alter_user_token"),
    ]

    operations = [
        migrations.RunPython(role_forwards_func, role_reverse_func),
    ]
