version: "3.0"

services:
  gunicorn:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "no"
    volumes:
      # hot dev
      # - .:/opt/app
      # sqlite
      - db:/opt/app/db
    ports:
      - 8000:8000

volumes:
  db: