# Generated by Django 4.1.2 on 2022-11-01 19:40

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations
from django.db.models import Q


def pm_forwards_func(apps, schema_editor):
    """
    Add project-manager perms
    """
    # since create signals works with `post_migrate` we need to create them manually
    emit_post_migrate_signal(1, False, "default")

    Project = apps.get_model("projects", "Project")
    ProjectMember = apps.get_model("projects", "ProjectMember")
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias

    content_type = ContentType.objects.get_for_model(Project)
    member_content_type = ContentType.objects.get_for_model(ProjectMember)

    project_permissions = Permission.objects.using(db_alias).filter(
        Q(content_type=content_type) | Q(content_type=member_content_type)
    )

    project_manger = Group.objects.using(db_alias).get(name="Project Manager")
    project_manger.permissions.add(*project_permissions.values_list("pk", flat=True))


def pm_reverse_func(apps, schema_editor):
    """
    Remove project-manager perms
    """
    Project = apps.get_model("projects", "Project")
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias

    content_type = ContentType.objects.get_for_model(Project)
    project_permissions = Permission.objects.using(db_alias).filter(
        content_type=content_type
    )
    project_manger = Group.objects.using(db_alias).get(name="Project Manager")
    project_manger.permissions.remove(*project_permissions.values_list("pk", flat=True))


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "__first__"),
        ("accounts", "0004_auto_20221101_1551"),
        ("projects", "0003_alter_project_slug"),
    ]

    operations = [
        migrations.RunPython(pm_forwards_func, pm_reverse_func),
    ]
